"""unique field

Revision ID: 96073b7ab6ef
Revises: 1595b70f4d40
Create Date: 2024-04-17 20:24:46.174612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96073b7ab6ef'
down_revision = '1595b70f4d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['document_number'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
